### PR TITLE
Implement Into for Data struct to allow conversion

### LINKED ISSUE #25: Allow Conversion between shio::request::Body and hyper::Body
This may already be handled in another way, but I can't for the life of me work it out.

Using the [HTTP Stream](https://github.com/mehcode/shio-rs/blob/master/examples/proxy/src/main.rs) example, say you wanted to convert this into a POST request and include the body.

You'd do something like this:

```
    let mut client_req = Request::new(ctx.method().clone(), "http://example.com".parse().unwrap());
    client_req.headers_mut().extend(ctx.headers().iter());
    client_req.set_body(ctx.body());
```

Only the issue is that you can't convert `shio::request::Body` to `hyper::Body`:

```
error[E0277]: the trait bound `hyper::Body: std::convert::From<shio::request::Body>` is not satisfied
  --> src/main.rs:17:16
   |
17 |     client_req.set_body(ctx.body());
   |                ^^^^^^^^ the trait `std::convert::From<shio::request::Body>` is not implemented for `hyper::Body`
```

### PR DESCRIPTION
**Pull request by cetra3**
Resolves https://github.com/mehcode/shio-rs/issues/25

### CODE REVIEW

**Comment by mehcode** [comment]
@cetra3 Thanks for these. Really busy this week but I'll get this merged before the next release.

**Comment by cetra3** [comment]
No worries. I can live on my fork until you're ready!

**Comment by mehcode** [comment]
@cetra3 :wave: (saw you booped the button) 

To keep you and others in the loop. I've been waiting for tokio 0.2 / futures 0.2 before working on the next big release of this as I'll likely have to make a few breaking changes and a ton of internal work.

**Comment by cetra3** [comment]
Sorry was just confirming that this change didn't break travis.  

Happy to close this off if you think that the internals are going to change substantially.

**Pull request closed without merging**
